### ISSUE TITLE
Break with placeholder it statement

### ISSUE THREAD

**Issue by SBoudrias** [mattphillips/babel-jest-assertions#4]
**Bug**

- `babel-jest-assertions` version: 0.0.2

Relevant code or config

```javascript
describe('<Component />', () => {
  it('handles click events');
  it('handles mouse out events');
});
```

```
  ● Test suite failed to run

    TypeError: /Users/sboudrias/workspace/appannie/aa-react/containers/SuperGrid/test.js: Cannot read property 'body' of undefined

      at PluginPass.ExpressionStatement (node_modules/babel-jest-assertions/dist/index.js:47:55)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)
```

Basically, `babel-jest-assertions` assumes all `it()` statement has a function body. This isn't necessary always the case, sometime you might create a series of `it()` statement as placeholder to clearly plan each things to tests. I think this plugin should handle this case properly and at least not fail when it happens.

Thanks!

**Comment by mattphillips** [comment]
Hey @SBoudrias nice catch! I've just published a fix for this in version 0.0.3 if you upgrade it should be sorted :smile:
